# insertion d'info dans la table armors

INSERT INTO `Armors`(`Name`,`Url`)VALUES('Ash','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Ash.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Atlas','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Atlas.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Banshee','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Banshee.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Baruuk','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/BARUUK.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Chroma','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Chroma.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Ember','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Ember.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Equinox','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Equinox.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Excalibur','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Excalibur.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Frost','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Frost.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Gara','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Gara.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Garuda','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Garuda.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Harrow','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Harrow.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Hildryn','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Hildryn.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Hydroid','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Hydroid.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Inaros','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Inaros.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Ivara','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Ivara.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Khora','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Khora.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Limbo','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Limbo.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Loki','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Loki.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Mag','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Mag.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Mesa','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Mesa.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Mirage','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Mirage.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Nekros','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Nekros.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Nezha','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Nezha.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Nidus','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Nidus.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Nova','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Nova.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Nyx','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Nyx.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Oberon','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Oberon.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Octavia','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Octavia.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Revenant','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Revenant.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Rhino','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Rhino.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Saryn','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Saryn.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Titania','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Titania.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Trinity','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Trinity.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Valkyr','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Valkyr.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Vauban','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Vauban.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Volt','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Volt.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Wisp','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Wisp.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Wukong','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Wukong.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Zephyr','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Zephyr.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Ash Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/Ash.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Banshee Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/BansheePrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Chroma Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/ChromaPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Ember Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/EmberPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Equinox Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/EquinoxPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Excalibur Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/ExcaliburPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Frost Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/FrostPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Hydroid Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/HydroidPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Limbo Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/LimboPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Loki Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/LokiPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Mag Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/MagPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Mesa Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/MesaPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Mirage Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/MiragePrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Nekros Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/NekrosPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Nova Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/NovaPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Nyx Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/NyxPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Oberon Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/OberonPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Rhino Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/RhinoPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Saryn Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/SarynPrim.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Trinity Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/TrinityPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Valkyr Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/ValkyrPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Vauban Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/vaubanPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Volt Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/VoltPrime.webm');
INSERT INTO `Armors`(`Name`,`Url`)VALUES('Zephyr Prime','https://n9e5v4d8.ssl.hwcdn.net/uploads/warframes/videos/ZephyrPrime.webm');



