# insertion d'info dans la table armors

INSERT INTO `Armors`(`name`,`url`)VALUES('Ash','assets/Videos/Ash.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Atlas','assets/Videos/Atlas.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Banshee','assets/Videos/Banshee.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Baruuk','assets/Videos/BARUUK.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Chroma','assets/Videos/Chroma.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Ember','assets/Videos/Ember.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Equinox','assets/Videos/Equinox.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Excalibur','assets/Videos/Excalibur.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Frost','assets/Videos/Frost.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Gara','assets/Videos/Gara.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Garuda','assets/Videos/Garuda.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Harrow','assets/Videos/Harrow.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Hildryn','assets/Videos/Hildryn.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Hydroid','assets/Videos/Hydroid.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Inaros','assets/Videos/Inaros.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Ivara','assets/Videos/Ivara.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Khora','assets/Videos/Khora.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Limbo','assets/Videos/Limbo.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Loki','assets/Videos/Loki.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Mag','assets/Videos/Mag.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Mesa','assets/Videos/Mesa.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Mirage','assets/Videos/Mirage.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Nekros','assets/Videos/Nekros.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Nezha','assets/Videos/Nezha.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Nidus','assets/Videos/Nidus.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Nova','assets/Videos/Nova.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Nyx','assets/Videos/Nyx.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Oberon','assets/Videos/Oberon.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Octavia','assets/Videos/Octavia.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Revenant','assets/Videos/Revenant.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Rhino','assets/Videos/Rhino.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Saryn','assets/Videos/Saryn.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Titania','assets/Videos/Titania.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Trinity','assets/Videos/Trinity.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Valkyr','assets/Videos/Valkyr.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Vauban','assets/Videos/Vauban.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Volt','assets/Videos/Volt.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Wisp','assets/Videos/Wisp.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Wukong','assets/Videos/Wukong.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Zephyr','assets/Videos/Zephyr.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Ash Prime','assets/Videos/Ash.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Banshee Prime','assets/Videos/BansheePrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Chroma Prime','assets/Videos/ChromaPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Ember Prime','assets/Videos/EmberPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Equinox Prime','assets/Videos/EquinoxPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Excalibur Prime','assets/Videos/ExcaliburPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Frost Prime','assets/Videos/FrostPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Hydroid Prime','assets/Videos/HydroidPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Limbo Prime','assets/Videos/LimboPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Loki Prime','assets/Videos/LokiPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Mag Prime','assets/Videos/MagPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Mesa Prime','assets/Videos/MesaPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Mirage Prime','assets/Videos/MiragePrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Nekros Prime','assets/Videos/NekrosPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Nova Prime','assets/Videos/NovaPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Nyx Prime','assets/Videos/NyxPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Oberon Prime','assets/Videos/OberonPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Rhino Prime','assets/Videos/RhinoPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Saryn Prime','assets/Videos/SarynPrim.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Trinity Prime','assets/Videos/TrinityPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Valkyr Prime','assets/Videos/ValkyrPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Vauban Prime','assets/Videos/vaubanPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Volt Prime','assets/Videos/VoltPrime.webm');
INSERT INTO `Armors`(`name`,`url`)VALUES('Zephyr Prime','assets/Videos/ZephyrPrime.webm');



